import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {
	MenuAlt1Icon,
	ShoppingCartIcon
} from '@heroicons/react/solid'
import { useState } from 'react';

const Layout = ({title, page, children}) => {
	const [showMenu, setshowMenu] = useState(false)
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
        		<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="fixed top-0 left-0 w-full font-main z-[1000]">
				<div className="relative w-full h-16 md:px-20 px-10 bg-white flex justify-between items-center shadow z-50">
					<div onClick={() => setshowMenu(!showMenu)} className="md:hidden block cursor-pointer">
						<MenuAlt1Icon className="w-7" />
					</div>
					<div className="flex h-full items-center py-2">
						<span className="mx-2 grid items-center">
							<Image
								src="/logo.svg"
								height={45}
								width={45}
							/>
						</span>
						<div className="w-[1.4px] h-full bg-black"></div>
						<span className="mx-2 text-base">GameSoup.in</span>
					</div>
					<nav className="md:flex text-lg hidden">
						<div className={`px-3 cursor-pointer ${(page == "home") ? "border-b-2 border-myOrange" : null}`} ><Link href="/"><a>Home</a></Link></div>
						<div className={`px-3 cursor-pointer ${(page == "hardware") ? "border-b-2 border-myOrange" : null}`}><Link href="/hardware"><a>Hardware</a></Link></div>
						<div className={`px-3 cursor-pointer ${(page == "games") ? "border-b-2 border-myOrange" : null}`}><Link href="/games"><a>Games</a></Link></div>
						<div className={`px-3 cursor-pointer ${(page == "contact") ? "border-b-2 border-myOrange" : null}`}><Link href="/contact"><a>Contact</a></Link></div>
					</nav>
					<Link href="/cart"><a><ShoppingCartIcon className="w-7"/></a></Link>
				</div>
				{/* mobile nav */}
				<div className="relative w-full text-white">
					<div className={`absolute z-40 top-0 left-0 w-full h-screen ${showMenu ? "block" : "hidden"}`} onClick={() => setshowMenu(false)} />
					<div className={`absolute z-40 top-0 left-0 w-full bg-myBlue-norm duration-200 transition-transform transform ${showMenu ? null : "-translate-y-full"}`}>
						<nav className="text-lg">
							<div className={`py-3 grid justify-center ${(page == "home") ? "bg-myBlue-wh" : null}`} ><Link href="/" ><a>Home</a></Link></div>
							<div className={`py-3 grid justify-center ${(page == "hardware") ? "bg-myBlue-wh" : null}`}><Link href="/hardware"><a>Hardware</a></Link></div>
							<div className={`py-3 grid justify-center ${(page == "games") ? "bg-myBlue-wh" : null}`}><Link href="/games"><a>Games</a></Link></div>
							<div className={`py-3 grid justify-center ${(page == "contact") ? "bg-myBlue-wh" : null}`}><Link href="/contact"><a>Contact</a></Link></div>
						</nav>
					</div>
				</div>
			</header>

			{/* children */}
			<main className="mt-16 font-main text-myBlack-dark">
				{children}
			</main>

			{/* footer */}
			<footer className="relative bottom-0 w-full bg-myGray-light flex flex-col items-center">
				<div className="relative w-full">
					<span className="absolute top-0 left-0 font-black text-9xl uppercase text-myGray-dark md:opacity-40 opacity-20">
						Thank you for visit
					</span>
					<div className="relative pt-20 grid md:grid-cols-4 grid-cols-1">
						<div className="h-full w-full md:flex hidden items-center justify-center">
							<span className="bg-myGray-light">
								<Image
									src="/logo.svg"
									height={156.57}
									width={200}
									className="opacity-30"
								/>
							</span>
						</div>
						<div className="flex md:flex-row flex-col md:p-0 px-10 capitalize text-lg text-myGray-dark justify-around md:col-start-2 md:col-end-5">
							<div>
								<span className="uppercase py-2 font-semibold text-[#939191]">contact us at</span>
								<ul>
									<li className="py-1"><a href="#" target="_blank">facebook</a></li>
									<li className="py-1"><a href="#" target="_blank">instagram</a></li>
									<li className="py-1"><a href="#" target="_blank">twitter</a></li>
								</ul>
							</div>
							<div>
								<span className="uppercase py-2 font-semibold text-[#939191]">products</span>
								<ul>
									<li className="py-1"><Link href="/"><a>popular games</a></Link></li>
									<li className="py-1"><Link href="/"><a>upcomming games</a></Link></li>
									<li className="py-1"><Link href="/"><a>new arrival</a></Link></li>
									<li className="py-1"><Link href="/"><a>play stations</a></Link></li>
									<li className="py-1"><Link href="/"><a>xbox</a></Link></li>
									<li className="py-1"><Link href="/"><a>accessories</a></Link></li>
								</ul>
							</div>
							<div>
								<span className="uppercase py-2 font-semibold text-[#939191]">website</span>
								<ul>
									<li className="py-1"><Link href="/"><a>Home</a></Link></li>
									<li className="py-1"><Link href="/"><a>Hardware</a></Link></li>
									<li className="py-1"><Link href="/"><a>games</a></Link></li>
									<li className="py-1"><Link href="/"><a>contact us</a></Link></li>
									<li className="py-1"><Link href="/"><a>cart</a></Link></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				{/* credits */}
				<div className="relative w-[95%] md:px-10 px-5 py-4 mt-3 border-t border-myGray-dark flex justify-between">
					<span className="text-myGray-dark">Made with ♡ by Shubham & Punit (APS Hisar)</span>
					<span className="text-myGray-dark">©All rights reserved 2021</span>
				</div>
			</footer>
		</>
	)
};

export default Layout;